// <auto-generated />
using EntityWorkers.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityWorkers.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20231128104254_ChangePrimaryKeyInWorkersCountry")]
    partial class ChangePrimaryKeyInWorkersCountry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityWorkers.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkersCityCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WorkersCountryCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("WorkersCityCity");

                    b.HasIndex("WorkersCountryCountry");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("EntityWorkers.Models.WorkersCity", b =>
                {
                    b.Property<string>("City")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("City");

                    b.ToTable("WorkersCities");
                });

            modelBuilder.Entity("EntityWorkers.Models.WorkersCountry", b =>
                {
                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Country");

                    b.ToTable("WorkersCountries");
                });

            modelBuilder.Entity("EntityWorkers.Models.Worker", b =>
                {
                    b.HasOne("EntityWorkers.Models.WorkersCity", "City")
                        .WithMany("workers")
                        .HasForeignKey("WorkersCityCity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityWorkers.Models.WorkersCountry", "Country")
                        .WithMany("workers")
                        .HasForeignKey("WorkersCountryCountry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("EntityWorkers.Models.WorkersCity", b =>
                {
                    b.Navigation("workers");
                });

            modelBuilder.Entity("EntityWorkers.Models.WorkersCountry", b =>
                {
                    b.Navigation("workers");
                });
#pragma warning restore 612, 618
        }
    }
}
